(()=>{const root=document.getElementById("philoAnnaleWork");if(!root)return;const id=new URLSearchParams(location.search).get("id");let hit=null,set=null;for(const s of window.PHILO_ANNALES_2026||[]){const x=s.subjects.find(v=>v.id===id);if(x){hit=x;set=s;break;}}if(!hit){root.innerHTML='<section class="pagehead"><div><h1>Sujet introuvable.</h1><p><a href="philosophie-annales.html">Revenir aux annales →</a></p></div></section>';return;}
document.title=hit.title+" | Annale philosophie 2026 | Commentaire Plan";
const safe=x=>String(x==null?"":x).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const diss=hit.type==="dissertation";
const head='<section class="pagehead"><div><div class="kicker">PHILOSOPHIE · BAC 2026 · '+safe(set.center)+'</div><h1>'+safe(hit.title)+'</h1><p class="lede">'+(diss?"Travaillez le sujet en cinq étapes, sur un brouillon. Le corrigé est en bas : ne l’ouvrez qu’après votre essai.":"Lisez d’abord le texte dans le sujet officiel, deux fois, crayon en main. Puis travaillez-le en cinq étapes. Le corrigé est en bas : ne l’ouvrez qu’après votre essai.")+'</p></div><aside class="side-note"><p><strong>'+(diss?"Dissertation":"Explication de texte")+'</strong><br>'+safe(set.code)+'</p><p><a href="'+set.source+'">Sujet officiel (PDF) ↗</a></p></aside></section>';
const step=(k,h,i,kind,rows)=>'<section class="exercise-wrap"><article class="exercise"><div class="kicker">'+k+'</div><h2>'+h+'</h2><p class="instruction">'+i+'</p><textarea rows="'+rows+'" data-feedback-kind="'+kind+'"></textarea></article></section>';
const p=(label,txt)=>txt?'<p><strong>'+label+' :</strong> '+safe(txt)+'</p>':'';
if(diss){
const pl=hit.plan||[];
const corr=hit.pb?'<section class="exercise-wrap"><article class="exercise"><div class="kicker">APRÈS VOTRE ESSAI</div><h2>Un corrigé possible.</h2><details class="correction"><summary>Comparer avec votre travail</summary>'+
p("Les mots du sujet",hit.mots)+p("Ce que la notion demande",hit.demande)+p("Première réponse",hit.oui)+p("Réponse contraire",hit.non)+p("Problématique",hit.pb)+
(pl.length===6?'<p><strong>Un plan possible.</strong></p><div class="sequence-spec"><p><strong>I.</strong> '+safe(pl[0])+'</p><p><em>Transition :</em> '+safe(pl[1])+'</p><p><strong>II.</strong> '+safe(pl[2])+'</p><p><em>Transition :</em> '+safe(pl[3])+'</p><p><strong>III.</strong> '+safe(pl[4])+'</p><p><em>Ce qui reste, pour la conclusion :</em> '+safe(pl[5])+'</p></div>':'')+
'<p class="micro">Ce n’est pas la seule réponse juste : une autre problématique est bonne si elle passe le test du gant.</p></details></article></section>':'';
root.innerHTML=head+
step('1 · LIRE LE SUJET','Que demandent exactement ses mots ?','Relevez les petits mots qui comptent (« peut-on », « faut-il », « sans », « nous »…). Puis écrivez l’idée que le sujet invite d’abord à accepter.','philo-reponse',4)+
step('2 · CE QUE LA NOTION DEMANDE','Quelles deux choses la notion demande-t-elle à la fois ?','Sans citer d’auteur, donnez deux choses que la notion principale demande dans son sens courant, et dites pourquoi elles se gênent. <a class="official-link" href="philosophie-problematisation.html#matrice">Le tableau des notions →</a>','philo-consequence',4)+
step('3 · CE QUE CHAQUE RÉPONSE PERD','Poussez chaque réponse jusqu’au bout.','Que perd la première réponse ? Que perd la réponse contraire ? Si une seule perd quelque chose, revenez à l’étape 2.','philo-cout',5)+
step('4 · LA PROBLÉMATIQUE','Une seule question, qui laisse les deux réponses ouvertes.','Mettez face à face les deux réponses et ce qu’elles perdent. Ne recopiez pas « peut-on » ou « faut-il ».','philo-problematique',4)+
step('5 · LE PLAN','I → transition → II → transition → III.','Écrivez l’idée de chaque partie et les deux questions de transition. La troisième partie ne choisit pas un camp : elle cherche une réponse qui perde moins. <a class="official-link" href="philosophie-operations.html">Les sept opérations →</a>','philo-plan',10)+
corr+
'<section class="offer-band"><div class="kicker">AVANT DE RÉDIGER</div><h2>Le test du gant.</h2><div class="sequence-spec"><p><strong>Aucun doigt ne manque :</strong> chaque mot du sujet travaille-t-il dans ma problématique ?</p><p><strong>Aucun doigt en trop :</strong> ai-je évité d’ajouter une notion que le sujet ne contient pas ?</p><p><strong>Les deux réponses restent ouvertes :</strong> chacune perd-elle quelque chose (pas de « comment pourrait-on… si… ») ?</p><p><strong>On reconnaît le sujet :</strong> le retrouve-t-on sans qu’il soit recopié ?</p><p><strong>D’une traite :</strong> une seule question, une trentaine de mots au plus ?</p><p><strong>Elle donne le plan :</strong> I défend une réponse, II part de ce qu’elle perd, III cherche une réponse qui perde moins ?</p></div><p class="micro"><strong>Sans IA :</strong> les étapes, le corrigé et ce test suffisent. <strong>Avec IA :</strong> un retour personnalisé peut vérifier votre problématique ; il ne produit pas le plan à votre place.</p></section>';
}else{
const corr=hit.these?'<section class="exercise-wrap"><article class="exercise"><div class="kicker">APRÈS VOTRE ESSAI</div><h2>Un corrigé possible.</h2><details class="correction"><summary>Comparer avec votre travail</summary>'+
p("Le problème",hit.probleme)+p("La thèse",hit.these)+
((hit.moments||[]).length?'<p><strong>Les moments du texte :</strong></p><ol>'+hit.moments.map(m=>'<li>'+safe(m)+'</li>').join("")+'</ol>':'')+
p("Ce que fait le texte",hit.operation)+p("Dans une dissertation",hit.reemploi)+
'<p class="micro">Ce corrigé résume le texte avec nos mots : relisez toujours le texte lui-même dans le sujet officiel.</p></details></article></section>':'';
root.innerHTML=head+
step('1 · LE PROBLÈME','À quelle difficulté le texte répond-il ?','En une ou deux phrases : quelle question l’auteur se pose-t-il, et pourquoi n’a-t-elle pas de réponse évidente ?','philo-texte-probleme',4)+
step('2 · LA THÈSE','Quelle réponse l’auteur défend-il ?','Une phrase précise, sans résumer tout le passage.','philo-texte-these',3)+
step('3 · LES MOMENTS','Comment le texte avance-t-il ?','Découpez le texte en trois à cinq moments. Pour chacun, une phrase : ce que l’auteur fait à cet endroit (il affirme, explique, donne un exemple, répond à une objection, conclut).','philo-texte-moments',6)+
step('4 · CE QUE FAIT LE TEXTE','Quelle opération l’auteur accomplit-il ?','Distingue-t-il deux plans, inverse-t-il un rapport, déplace-t-il la difficulté, transforme-t-il un concept ? Dites ce que cela lui permet de résoudre.','philo-operation',5)+
step('5 · DANS UNE DISSERTATION','À quoi ce texte pourrait-il servir ?','Choisissez un sujet de dissertation, puis expliquez en une phrase dans quelle partie et pour quoi faire vous utiliseriez ce texte.','philo-reemploi',4)+
corr+
'<section class="offer-band"><div class="kicker">AVANT DE RÉDIGER</div><h2>Quatre vérifications.</h2><div class="sequence-spec"><p>Mon problème explique-t-il pourquoi le texte avait quelque chose à résoudre ?</p><p>Ma thèse dit-elle ce que l’auteur établit, sans résumer le passage ?</p><p>Mes moments suivent-ils l’ordre du texte, chacun avec son rôle ?</p><p>L’opération repérée est-elle précise, et liée à ce qu’elle résout ici ?</p></div><p class="micro"><strong>Sans IA :</strong> le sujet officiel, les étapes et le corrigé suffisent. <strong>Avec IA :</strong> un retour personnalisé peut vérifier la précision de votre problème et de votre thèse ; il ne remplace pas l’explication du texte.</p></section>';
}
root.insertAdjacentHTML("beforeend",'<section class="offer-band"><p><a href="philosophie-annales.html">← Revenir à toutes les annales</a></p></section>');
})();
