(()=>{const root=document.getElementById("philoAnnaleWork");if(!root)return;const id=new URLSearchParams(location.search).get("id");let hit=null,set=null;for(const s of window.PHILO_ANNALES_2026||[]){const x=s.subjects.find(v=>v.id===id);if(x){hit=x;set=s;break;}}if(!hit){root.innerHTML='<section class="pagehead"><div><h1>Sujet introuvable.</h1><p><a href="philosophie-annales.html">Revenir aux annales →</a></p></div></section>';return;}
document.title=hit.title+" | Annale philosophie 2026 | Commentaire Plan";
const safe=x=>String(x).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const head='<section class="pagehead"><div><div class="kicker">PHILOSOPHIE · 2026 · '+safe(set.center)+'</div><h1>'+safe(hit.title)+'</h1><p class="lede">'+(hit.type==="dissertation"?"Travaillez le sujet par opérations séparées avant d’assembler le devoir.":"Lisez d’abord le texte dans le PDF officiel, puis travaillez son problème, sa thèse et son opération philosophique.")+'</p></div><aside class="side-note"><p><strong>'+ (hit.type==="dissertation"?"Dissertation":"Explication de texte") +'</strong><br>'+safe(set.code)+'</p><p><a href="'+set.source+'">Sujet officiel PDF ↗</a></p></aside></section>';
if(hit.type==="dissertation"){
const step=(k,h,i,kind,rows)=>'<section class="exercise-wrap"><article class="exercise"><div class="kicker">'+k+'</div><h2>'+h+'</h2><p class="instruction">'+i+'</p><textarea rows="'+rows+'" data-feedback-kind="'+kind+'"></textarea></article></section>';
const corr=hit.pb?'<section class="exercise-wrap"><article class="exercise"><div class="kicker">APRÈS VOTRE ESSAI</div><h2>Une problématique possible.</h2><details class="correction"><summary>Comparer avec votre travail</summary><p><strong>Les mots du sujet :</strong> '+safe(hit.mots)+'</p><p><strong>Le chiasme :</strong> '+safe(hit.tension)+'</p><p><strong>Problématique :</strong> '+safe(hit.pb)+'</p><p class="micro">Le problème est le même pour tous ; sa formulation peut varier. Une autre formulation du même chiasme est aussi juste si elle passe le test du gant.</p></details></article></section>':'';
root.innerHTML=head+
step('1 · LIRE LE SUJET','Que demandent exactement ses mots ?','Relevez l’opérateur (« peut-on », « faut-il »…), la relation entre les notions et les petits mots qui comptent (article, pronom, préposition). Puis écrivez l’idée que le sujet invite spontanément à accepter.','philo-reponse',4)+
step('2 · LES DEUX EXIGENCES','Quelles deux exigences la notion réunit-elle ?','Sans auteur, donnez deux choses que la notion principale exige dans son sens courant et qui sont difficiles à tenir ensemble. <a class="official-link" href="philosophie-problematisation.html#matrice">Matrice des notions →</a>','philo-consequence',4)+
step('3 · LE CHIASME','Sur quoi chaque réponse s’appuie-t-elle, et que détruit-elle ?','Poussez l’idée spontanée jusqu’au bout : sur quelle exigence de la notion s’appuie-t-elle, et laquelle détruit-elle ? Faites de même avec l’idée contraire. Si une seule réponse échoue, revenez à l’étape 2.','philo-cout',5)+
step('4 · PROBLÉMATIQUE','Formulez la tension en une question.','Une seule question, ouverte, qui met face à face les deux paradoxes. L’opérateur du sujet ne doit pas y apparaître.','philo-problematique',4)+
step('5 · PLAN ET TRANSITIONS','I → ce que I détruit → II → ce qui reste → III.','Écrivez seulement les trois réponses de parties et les deux questions de transition.','philo-plan',10)+
corr+
'<section class="offer-band"><div class="kicker">AUTO-AUDIT SANS IA</div><h2>Le test du gant.</h2><div class="sequence-spec"><p><strong>Le chiasme :</strong> chaque réponse s’appuie-t-elle sur une exigence de la notion pour détruire l’autre ?</p><p><strong>Aucun doigt ne manque :</strong> chaque mot du sujet y travaille-t-il ?</p><p><strong>Aucun doigt en trop :</strong> rien n’est-il ajouté au sens courant des mots ?</p><p><strong>Les deux branches sont vraies :</strong> la réponse reste-t-elle ouverte (pas de « comment pourrait-on… si… ») ?</p><p><strong>On reconnaît la main :</strong> retrouve-t-on le sujet sans qu’il soit recopié ?</p><p><strong>D’une traite :</strong> une seule question, une trentaine de mots au plus ?</p></div></section><section class="offer-band"><div class="kicker">SANS IA / AVEC IA</div><p><strong>Sans IA :</strong> utilisez les étapes, la matrice et le test du gant. <strong>Avec IA :</strong> quand le retour personnalisé est disponible, il vérifie le chiasme et le gant sur votre problématique et vous fait reprendre votre formulation ; il ne produit pas le plan à votre place.</p></section>';
}else{
root.innerHTML=head+
'<section class="exercise-wrap"><article class="exercise"><div class="kicker">1 · PROBLÈME</div><h2>À quelle difficulté le texte répond-il ?</h2><p class="instruction">Après lecture du PDF officiel, formulez le problème en une ou deux phrases.</p><textarea rows="4" data-feedback-kind="philo-texte-probleme"></textarea></article></section>'+
'<section class="exercise-wrap"><article class="exercise"><div class="kicker">2 · THÈSE</div><h2>Quelle réponse l’auteur construit-il ?</h2><p class="instruction">Une phrase précise, sans résumé du passage.</p><textarea rows="4" data-feedback-kind="philo-texte-these"></textarea></article></section>'+
'<section class="exercise-wrap"><article class="exercise"><div class="kicker">3 · OPÉRATION</div><h2>Que fait philosophiquement le texte ?</h2><p class="instruction">Repérez une distinction, inversion, déplacement, processus, limitation ou autre opération, puis dites ce qu’elle résout ici.</p><textarea rows="6" data-feedback-kind="philo-operation"></textarea></article></section>'+
'<section class="exercise-wrap"><article class="exercise"><div class="kicker">4 · RÉEMPLOI</div><h2>Dans quelle dissertation cette idée pourrait-elle servir ?</h2><p class="instruction">Inventez ou choisissez un sujet, puis expliquez en une phrase l’usage précis de ce texte.</p><textarea rows="5" data-feedback-kind="philo-reemploi"></textarea></article></section>'+
'<section class="offer-band"><div class="kicker">AUTO-AUDIT SANS IA</div><h2>Quatre contrôles.</h2><div class="sequence-spec"><p>Mon problème explique-t-il pourquoi le texte avait quelque chose à résoudre ?</p><p>Ma thèse dit-elle ce que l’auteur établit, sans résumer le passage ?</p><p>L’opération repérée est-elle précise et liée à ce qu’elle résout ici ?</p><p>Le réemploi explique-t-il exactement à quoi le texte servirait dans une dissertation ?</p></div></section><section class="offer-band"><div class="kicker">SANS IA / AVEC IA</div><p><strong>Sans IA :</strong> le PDF officiel, les quatre questions et l’auto-audit suffisent pour faire le travail. <strong>Avec IA :</strong> un retour personnalisé est surtout utile pour vérifier la précision du problème, de la thèse et de « ce que l’opération résout ici » ; il ne doit pas remplacer l’explication du texte.</p></section>';
}
root.insertAdjacentHTML("beforeend",'<section class="offer-band"><p><a href="philosophie-annales.html">← Revenir à toutes les annales</a></p></section>');
})();