window.PROCEDES_CORPUS = [
{id:"nerval-soleil-noir",auteur:"Gérard de Nerval",oeuvre:"El Desdichado",citation:"Soleil noir de la Mélancolie",element:"« Soleil noir »",procedures:["Oxymore"],effet:"La mélancolie devient une lumière noire : elle éclaire le monde du poète, mais tout ce qu’elle éclaire apparaît sombre."},
{id:"verlaine-pleure",auteur:"Paul Verlaine",oeuvre:"Il pleure dans mon cœur",citation:"Il pleure dans mon cœur / Comme il pleut sur la ville.",element:"« Il pleure dans mon cœur / Comme il pleut sur la ville. »",procedures:["Comparaison","Parallélisme"],effet:"La pluie sur la ville devient l’image de la tristesse intérieure du poète.",effet2:"La même construction rapproche directement le cœur et la ville."},
{id:"flaubert-bovary",auteur:"Gustave Flaubert",oeuvre:"Madame Bovary",citation:"mourir / habiter Paris",element:"« mourir » / « habiter Paris »",procedures:["Antithèse"],effet:"Le rêve d’une autre vie et le désir de mourir sont mis sur le même plan : Emma ne supporte plus sa vie présente."},
{id:"corneille-rage",auteur:"Pierre Corneille",oeuvre:"Le Cid",citation:"Ô rage ! ô désespoir ! ô vieillesse ennemie !",element:"« Ô rage ! ô désespoir ! ô vieillesse ennemie ! »",procedures:["Apostrophe","Anaphore","Accumulation","Personnification"],effet:"La parole fait entendre immédiatement l’émotion et transforme les souffrances en interlocuteurs qui accablent Don Diègue."},
{id:"diderot-eternites",auteur:"Denis Diderot",oeuvre:"Salon de 1767",citation:"Je marche entre deux éternités.",element:"« Je marche entre deux éternités. »",procedures:["Métaphore"],effet:"Le temps de la vie devient un espace très bref à traverser entre l’éternité d’avant la naissance et celle d’après la mort."},
{id:"diderot-tout",auteur:"Denis Diderot",oeuvre:"Salon de 1767",citation:"Tout s’anéantit, tout périt, tout passe.",element:"répétition de « tout » et série « s’anéantit / périt / passe »",procedures:["Anaphore","Accumulation"],effet:"La disparition concerne toute chose et ses formes se multiplient jusqu’à rendre l’effacement inévitable."},
{id:"barbey-silence",auteur:"Jules Barbey d’Aurevilly",oeuvre:"L’Ensorcelée",citation:"Un si vaste silence aurait dévoré tous les cris.",element:"« dévoré »",procedures:["Personnification"],effet:"Le silence devient une force vivante capable d’engloutir même les cris."},
{id:"barbey-imagination",auteur:"Jules Barbey d’Aurevilly",oeuvre:"L’Ensorcelée",citation:"L’imagination [...] la plus puissante réalité",element:"« l’imagination [...] la plus puissante réalité »",procedures:["Paradoxe"],effet:"Ce qui n’existe que dans l’imagination peut agir sur les hommes plus fortement que la réalité matérielle."},
{id:"beaumarchais-naitre",auteur:"Beaumarchais",oeuvre:"Le Mariage de Figaro",citation:"Vous vous êtes donné la peine de naître",element:"« donné la peine de naître »",procedures:["Ironie"],effet:"Figaro feint de présenter la naissance comme un mérite afin de ridiculiser un privilège obtenu sans aucun effort."},
{id:"lisle-pantouns-opposition",auteur:"Leconte de Lisle",oeuvre:"Pantouns malais",citation:"perles, beau col, mon amour / sang frais, écarlate, blême",element:"vocabulaire de l’amour et de la beauté / vocabulaire du sang et de la mort",procedures:["Opposition lexicale"],effet:"La beauté et l’amour côtoient la violence et la mort : la scène devient à la fois séduisante et inquiétante."},
{id:"lisle-parfume",auteur:"Leconte de Lisle",oeuvre:"Pantouns malais",citation:"L’odeur du sang parfume l’air.",element:"verbe « parfume »",procedures:["Choix lexical"],effet:"Une odeur de sang normalement répugnante est présentée comme un parfum agréable : la violence acquiert une beauté troublante."},
{id:"baudelaire-rue",auteur:"Charles Baudelaire",oeuvre:"À une passante",citation:"La rue [...] hurlait.",element:"verbe « hurlait »",procedures:["Personnification"],effet:"La rue devient un être vivant qui hurle ; le bruit de la ville apparaît agressif et presque menaçant."},
{id:"baudelaire-musique",auteur:"Charles Baudelaire",oeuvre:"La Musique",citation:"La musique souvent me prend comme une mer !",element:"« comme une mer »",procedures:["Comparaison"],effet:"La musique devient une puissance immense qui saisit le poète et l’emporte."},
{id:"baudelaire-douleur",auteur:"Charles Baudelaire",oeuvre:"Recueillement",citation:"Sois sage, ô ma Douleur, et tiens-toi plus tranquille.",element:"« ô ma Douleur » ; « Sois » ; « tiens-toi »",procedures:["Apostrophe","Impératif"],effet:"Le poète transforme sa douleur en interlocutrice et tente de lui commander pour reprendre prise sur elle."},
{id:"rimbaud-riviere",auteur:"Arthur Rimbaud",oeuvre:"Le Dormeur du val",citation:"où chante une rivière",element:"verbe « chante »",procedures:["Personnification"],effet:"La rivière semble avoir une voix ; le paysage paraît vivant, doux et paisible, ce qui fait d’abord croire à un simple sommeil."},
{id:"hugo-guerre",auteur:"Victor Hugo",oeuvre:"Les Contemplations",citation:"La guerre, cette gloire / Qu’on fait avec de la nuit.",element:"« gloire » / « nuit »",procedures:["Antithèse","Métaphore"],effet:"La gloire devrait être lumineuse ; le texte révèle la violence et la mort cachées derrière la gloire guerrière."},
{id:"anouilh-jardin",auteur:"Jean Anouilh",oeuvre:"Antigone",citation:"un jardin qui ne pense pas encore aux hommes",element:"« ne pense pas encore aux hommes »",procedures:["Personnification"],effet:"Le jardin semble vivre tranquillement avant l’arrivée des hommes ; « encore » suggère qu’ils vont venir troubler cette paix."},
{id:"proust-paradis",auteur:"Marcel Proust",oeuvre:"Le Temps retrouvé",citation:"Les vrais paradis sont les paradis qu’on a perdus.",element:"« vrais paradis » / « perdus »",procedures:["Paradoxe"],effet:"On comprend parfois pleinement le bonheur seulement lorsqu’on l’a perdu ; le souvenir transforme ce qui a disparu en paradis."},
{id:"cioran-noe",auteur:"Emil Cioran",oeuvre:"Syllogismes de l’amertume",citation:"Si Noé avait eu le don de lire dans l’avenir [...] il se fût sabordé.",element:"condition hypothétique et inversion du rôle de Noé",procedures:["Condition","Retournement paradoxal","Humour noir"],effet:"Celui qui devait sauver l’humanité aurait préféré empêcher sa survie : l’avenir de l’humanité est présenté comme si mauvais qu’il justifierait de ne pas la sauver."}
];

window.PROCEDES_MODES = {
  nommer:{title:"Nommer précisément",free:true,kind:"qcm-procede",lede:"Choisissez le procédé qui décrit exactement la construction de l’élément."},
  effet:{title:"Choisir l’effet ici",free:true,kind:"qcm-effet",lede:"Écartez les effets automatiques et choisissez ce que le procédé produit réellement dans ce passage."},
  reparer:{title:"Réparer une analyse faible",free:true,kind:"repair",lede:"Une analyse exacte mais vide vous est donnée. Expliquez ce qui manque, puis réparez-la."},
  chaine:{title:"Construire la chaîne complète",free:true,kind:"chain",lede:"À partir de la citation, reconstruisez élément textuel → procédé → effet."},
  multiples:{title:"Plusieurs procédés possibles",free:false,kind:"multiple",lede:"Repérez plusieurs analyses recevables dans une même citation et distinguez ce que chacune permet de voir."},
  comparer:{title:"Même procédé, effets différents",free:false,kind:"compare",lede:"Le même procédé n’a pas le même effet partout : comparez deux occurrences."},
  pertinent:{title:"Choisir le procédé pertinent",free:false,kind:"pertinent",lede:"Plusieurs observations peuvent être exactes ; choisissez celle qui sert le mieux l’idée à démontrer."},
  transfert:{title:"Transfert sans catégorie donnée",free:false,kind:"transfer",lede:"Citation nouvelle, manuel autorisé, aucune liste de procédés : construisez seul une analyse défendable."}
};