window.PROCEDES_CORPUS = [
{id:"nerval-soleil-noir",auteur:"Gérard de Nerval",oeuvre:"El Desdichado",annee:"1854",citation:"Ma seule étoile est morte, — et mon luth constellé / Porte le Soleil noir de la Mélancolie.",procedures:["Oxymore","Métaphore"],effet:"La mélancolie devient une lucidité sombre : elle fait voir clairement, mais ce qu’elle révèle est noir."},
{id:"verlaine-pleure",auteur:"Paul Verlaine",oeuvre:"Il pleure dans mon cœur, dans Romances sans paroles",annee:"1874",citation:"Il pleure dans mon cœur / Comme il pleut sur la ville.",procedures:["Métaphore","Comparaison","Parallélisme"],effet:"Le chagrin devient une pluie intérieure : l’état d’âme et le paysage se répondent jusqu’à se confondre."},
{id:"flaubert-bovary",auteur:"Gustave Flaubert",oeuvre:"Madame Bovary",annee:"1857",citation:"Elle souhaitait à la fois mourir et habiter Paris.",procedures:["Antithèse","Parallélisme"],effet:"Le parallélisme met au même niveau deux désirs incompatibles ; l’antithèse révèle qu’Emma veut surtout échapper absolument à sa vie présente."},
{id:"corneille-rage",auteur:"Pierre Corneille",oeuvre:"Le Cid",annee:"1637",citation:"Ô rage ! ô désespoir ! ô vieillesse ennemie !",procedures:["Anaphore","Apostrophe","Personnification"],effet:"« Ô » relance trois élans de plainte ; les apostrophes donnent corps aux affects ; « ennemie » fait de la vieillesse un adversaire. Le malheur devient combat."},
{id:"diderot-eternites",auteur:"Denis Diderot",oeuvre:"Salon de 1767",annee:"1767",citation:"Je marche entre deux éternités.",procedures:["Métaphore d’ensemble","Contraste d’échelle"],effet:"Un geste humain ordinaire et limité se trouve pris entre deux infinis : la phrase fait sentir la brièveté vertigineuse d’une vie."},
{id:"diderot-tout",auteur:"Denis Diderot",oeuvre:"Salon de 1767",annee:"1767",citation:"Tout s’anéantit, tout périt, tout passe.",procedures:["Anaphore","Accumulation parallèle"],effet:"L’anaphore étend la disparition à tout ; les trois verbes l’enchaînent sans répit : rien ne résiste au temps."},
{id:"barbey-silence",auteur:"Jules Barbey d’Aurevilly",oeuvre:"L’Ensorcelée",annee:"1854",citation:"Un si vaste silence aurait dévoré tous les cris.",procedures:["Antithèse","Métaphore","Personnification"],effet:"Les cris, qui devraient briser le silence, sont eux-mêmes « dévorés » : le silence devient une force qui abolit jusqu’à son contraire."},
{id:"barbey-imagination",auteur:"Jules Barbey d’Aurevilly",oeuvre:"L’Ensorcelée",annee:"1854",citation:"L’imagination continuera d’être […] la plus puissante réalité qu’il y ait dans la vie des hommes.",procedures:["Paradoxe","Superlatif"],effet:"Le paradoxe fait de l’imagination une « réalité » ; le superlatif la place au-dessus des faits : ce que l’homme imagine peut gouverner sa vie."},
{id:"beaumarchais-naitre",auteur:"Beaumarchais",oeuvre:"Le Mariage de Figaro",annee:"1784",citation:"Vous vous êtes donné la peine de naître, et rien de plus.",procedures:["Ironie"],effet:"La fausse louange transforme la naissance en prétendu mérite : le privilège aristocratique apparaît absurde."},
{id:"lisle-pantouns-opposition",auteur:"Leconte de Lisle",oeuvre:"Pantouns malais, dans Poèmes tragiques",annee:"1884",citation:"Voici des perles de Mascate / Pour ton beau col, ô mon amour ! / Un sang frais ruisselle, écarlate…",procedures:["Opposition lexicale","Juxtaposition"],effet:"Le raffinement amoureux et le sang surgissent dans le même mouvement : beauté et violence deviennent inséparables."},
{id:"lisle-parfume",auteur:"Leconte de Lisle",oeuvre:"Pantouns malais, dans Poèmes tragiques",annee:"1884",citation:"L’odeur du sang parfume l’air.",procedures:["Détournement lexical","Métaphore verbale"],effet:"Le verbe valorisant « parfume » s’applique au sang : la violence reçoit une séduction troublante."},
{id:"baudelaire-rue",auteur:"Charles Baudelaire",oeuvre:"À une passante, dans Les Fleurs du mal",annee:"1861",citation:"La rue assourdissante autour de moi hurlait.",procedures:["Personnification"],effet:"« Hurlait » donne à la rue une voix animale et agressive : le vacarme urbain devient une force qui assaille le poète."},
{id:"baudelaire-musique",auteur:"Charles Baudelaire",oeuvre:"La Musique, dans Les Fleurs du mal",annee:"1857",citation:"La musique souvent me prend comme une mer !",procedures:["Comparaison","Personnification"],effet:"La musique acquiert la puissance d’une mer : elle saisit, enveloppe et emporte le poète."},
{id:"baudelaire-douleur",auteur:"Charles Baudelaire",oeuvre:"Recueillement",annee:"1866",citation:"Sois sage, ô ma Douleur, et tiens-toi plus tranquille.",procedures:["Apostrophe","Personnification","Impératifs"],effet:"En faisant de sa douleur un interlocuteur, le poète peut lui donner des ordres : la parole transforme la souffrance en tentative de maîtrise."},
{id:"rimbaud-riviere",auteur:"Arthur Rimbaud",oeuvre:"Le Dormeur du val",annee:"1870",citation:"C’est un trou de verdure où chante une rivière.",procedures:["Personnification"],effet:"Le bruit de l’eau devient un chant : le paysage paraît vivant, paisible et accueillant."},
{id:"hugo-guerre",auteur:"Victor Hugo",oeuvre:"Les Contemplations",annee:"1856",citation:"La guerre, cette gloire / Qu’on fait avec de la nuit.",procedures:["Apposition","Métaphore","Opposition implicite"],effet:"« Gloire » donne d’abord à la guerre son nom prestigieux ; « nuit » révèle la matière sombre de cette gloire. La formule retourne l’éloge en accusation."},
{id:"anouilh-jardin",auteur:"Jean Anouilh",oeuvre:"Antigone",annee:"1944",citation:"C’est beau un jardin qui ne pense pas encore aux hommes.",procedures:["Personnification","Valeur de « encore »"],effet:"Le jardin reçoit une innocence propre ; « encore » annonce que l’arrivée des hommes va la menacer."},
{id:"proust-paradis",auteur:"Marcel Proust",oeuvre:"Le Temps retrouvé",annee:"1927",citation:"Les vrais paradis sont les paradis qu’on a perdus.",procedures:["Paradoxe"],effet:"Le paradoxe renverse la perte en révélation : on ne reconnaît pleinement le paradis qu’après l’avoir perdu."},
{id:"cioran-noe",auteur:"Emil Cioran",oeuvre:"Syllogismes de l’amertume",annee:"1952",citation:"Si Noé avait eu le don de lire dans l’avenir, […] il se fût sabordé.",procedures:["Condition irréelle","Allusion biblique","Humour noir"],effet:"L’hypothèse retourne le récit du salut : s’il avait connu l’avenir, Noé aurait détruit l’arche au lieu de sauver l’humanité. Le sauvetage devient une erreur.",note:"Noé construit l’arche qui permet à l’humanité et aux animaux de survivre au Déluge. Se saborder = couler volontairement son propre navire."}
];

window.PROCEDES_MODES = {
  effetici:{title:"Procédé(s) → effet ici",free:true,kind:"effect-reference",lede:"Repérez tous les procédés utiles, puis formulez l’effet le plus précis et le plus bref possible avant de comparer avec l’effet de référence."},
  nommer:{title:"Nommer précisément",free:true,kind:"qcm-procede",lede:"Choisissez le procédé qui décrit exactement la construction de l’élément."},
  effet:{title:"Choisir l’effet ici",free:true,kind:"qcm-effet",lede:"Écartez les effets automatiques et choisissez ce que le procédé produit réellement dans ce passage."},
  reparer:{title:"Réparer une analyse faible",free:true,kind:"repair",lede:"Une analyse exacte mais vide vous est donnée. Expliquez ce qui manque, puis réparez-la."},
  chaine:{title:"Construire la chaîne complète",free:true,kind:"chain",lede:"À partir de la citation, reconstruisez élément textuel → procédé → effet."},
  multiples:{title:"Plusieurs procédés possibles",free:false,kind:"multiple",lede:"Repérez plusieurs analyses recevables dans une même citation et distinguez ce que chacune permet de voir."},
  comparer:{title:"Même procédé, effets différents",free:false,kind:"compare",lede:"Le même procédé n’a pas le même effet partout : comparez deux occurrences."},
  pertinent:{title:"Choisir le procédé pertinent",free:false,kind:"pertinent",lede:"Plusieurs observations peuvent être exactes ; choisissez celle qui sert le mieux l’idée à démontrer."},
  transfert:{title:"Transfert sans catégorie donnée",free:false,kind:"transfer",lede:"Citation nouvelle, manuel autorisé, aucune liste de procédés : construisez seul une analyse défendable."}
};
// Extraits d'annales officielles — entrées éditorialisées au même niveau que le corpus de référence.
window.PROCEDES_CORPUS.push(
{id:"annale-hialmar-neige-rouge",auteur:"Leconte de Lisle",oeuvre:"Le Cœur de Hialmar",annee:"1862",citation:"Une nuit claire, un vent glacé. La neige est rouge.",procedures:["Opposition chromatique","Juxtaposition"],effet:"Le rouge du sang envahit la blancheur attendue de la neige : le paysage porte immédiatement la bataille.",sourceAnnale:"Bac 2026 · Amérique du Nord",annaleHref:"bac-2026-amerique-du-nord-general-commentaire-leconte-de-lisle-le-coeur-de-hialmar.html"},
{id:"annale-hialmar-esprit-coule",auteur:"Leconte de Lisle",oeuvre:"Le Cœur de Hialmar",annee:"1862",citation:"Moi, je meurs. Mon esprit coule par vingt blessures.",procedures:["Métaphore verbale","Hyperbole"],effet:"La vie semble s’écouler hors du corps par les plaies : la mort devient une fuite irréversible.",sourceAnnale:"Bac 2026 · Amérique du Nord",annaleHref:"bac-2026-amerique-du-nord-general-commentaire-leconte-de-lisle-le-coeur-de-hialmar.html"},
{id:"annale-montaigne-echasses",auteur:"Montaigne",oeuvre:"Essais — Sur l’inégalité entre les hommes",annee:"1595",citation:"Mesurez cet homme sans ses échasses.",procedures:["Métaphore"],effet:"Les titres deviennent des échasses : ce qui grandit socialement l’homme ne l’agrandit pas lui-même.",sourceAnnale:"Bac 2025 · Amérique du Nord",annaleHref:"bac-2025-amerique-du-nord-general-commentaire-montaigne-essais.html"},
{id:"annale-montaigne-empire",auteur:"Montaigne",oeuvre:"Essais — Sur l’inégalité entre les hommes",annee:"1595",citation:"Il est à lui-même son empire.",procedures:["Métaphore"],effet:"La maîtrise de soi remplace les royaumes extérieurs : l’homme vaut par le pouvoir qu’il exerce sur lui-même.",sourceAnnale:"Bac 2025 · Amérique du Nord",annaleHref:"bac-2025-amerique-du-nord-general-commentaire-montaigne-essais.html"},
{id:"annale-duras-entre-deux",auteur:"Claire de Duras",oeuvre:"Édouard",annee:"1825",citation:"Une vapeur violette qui n’était plus le jour, et qui n’était pas encore l’obscurité.",procedures:["Parallélisme","Antithèse"],effet:"Le paysage reste suspendu entre jour et nuit : l’entre-deux de la lumière prépare celui de l’amour, proche mais impossible.",sourceAnnale:"Bac 2024 · Métropole",annaleHref:"bac-2024-metropole-general-commentaire-claire-de-duras-edouard.html"},
{id:"annale-duras-enivrait",auteur:"Claire de Duras",oeuvre:"Édouard",annee:"1825",citation:"La paix de ces campagnes, l’heure, le silence, l’expression de ce doux visage […] tout m’enivrait d’amour.",procedures:["Accumulation","Métaphore"],effet:"Le paysage entier devient une ivresse amoureuse : Édouard ne distingue plus ce qu’il voit de ce qu’il éprouve.",sourceAnnale:"Bac 2024 · Métropole",annaleHref:"bac-2024-metropole-general-commentaire-claire-de-duras-edouard.html"},
{id:"annale-duras-jamais",auteur:"Claire de Duras",oeuvre:"Édouard",annee:"1825",citation:"Jamais, jamais, nous ne serons rien l’un à l’autre !",procedures:["Répétition","Négation"],effet:"La répétition ferme l’avenir au moment même où leur proximité rend l’amour presque possible.",sourceAnnale:"Bac 2024 · Métropole",annaleHref:"bac-2024-metropole-general-commentaire-claire-de-duras-edouard.html"},
{id:"annale-racine-pleurs",auteur:"Jean Racine",oeuvre:"Bérénice, IV, 5",annee:"1670",citation:"Ou, si nous ne pouvons commander à nos pleurs, / Que la gloire du moins soutienne nos douleurs.",procedures:["Métaphore du commandement","Parallélisme"],effet:"Titus traite sa douleur comme une révolte à maîtriser : l’empereur voudrait régner jusque sur ses larmes.",sourceAnnale:"Bac 2023 · Amérique du Nord",annaleHref:"bac-2023-amerique-du-nord-general-commentaire-racine-berenice.html"},
{id:"annale-racine-deux-pleurs",auteur:"Jean Racine",oeuvre:"Bérénice, IV, 5",annee:"1670",citation:"Les pleurs d’un empereur et les pleurs d’une reine.",procedures:["Parallélisme","Anaphore"],effet:"La même construction égalise les deux souverains dans la souffrance au moment où Rome les sépare.",sourceAnnale:"Bac 2023 · Amérique du Nord",annaleHref:"bac-2023-amerique-du-nord-general-commentaire-racine-berenice.html"}
);
