const scales={
problematique:{title:'Problématiser.',bous:['Une phrase ou un court passage.','Vous repérez ce qu’on pouvait attendre et ce que le texte produit pourtant.','Une question qui garde les deux.'],lede:'Découvrez ce qui, dans le texte, demande une explication.',levels:['REPÉRER','CHOISIR','JUSTIFIER','FORMULER','TRANSFÉRER'],items:[
{name:'Chamfort',quote:'« La société est composée de deux grandes classes : ceux qui ont plus de dîners que d’appétit, et ceux qui ont plus d’appétit que de dîners. »',q:'Quel écart faut-il d’abord voir ?',opts:['Un texte sérieux / un texte comique','Une formule parfaitement équilibrée / une société profondément déséquilibrée','Les riches / les pauvres'],a:1,why:'Le troisième couple nomme le thème. Le deuxième fait apparaître le mécanisme singulier de la phrase : son équilibre verbal révèle un déséquilibre social.'},
{name:'La Rochefoucauld',quote:'« Rien n’empêche tant d’être naturel que l’envie de le paraître. »',q:'Quelle problématique conserve exactement le paradoxe ?',opts:['Pourquoi est-il difficile d’être naturel ?','Comment le désir de paraître naturel peut-il précisément empêcher de l’être ?','Comment l’auteur critique-t-il l’hypocrisie ?'],a:1,why:'La bonne question conserve les deux pôles contradictoires. Les autres généralisent ou déplacent le problème.'},
{name:'Pascal',quote:'« Le nez de Cléopâtre, s’il eût été plus court, toute la face de la terre aurait changé. »',q:'Pourquoi « Comment Pascal montre-t-il l’importance de Cléopâtre ? » est-elle insuffisante ?',opts:['Elle est trop courte.','Elle ne contient pas de procédé.','Elle perd le contraste entre une cause minuscule et une conséquence historique immense.'],a:2,why:'Une problématique n’est pas meilleure parce qu’elle est plus savante : elle est meilleure lorsqu’elle conserve ce qui rend le texte difficile à expliquer.'},
{name:'Hialmar',quote:'Un guerrier agonise après une défaite. Pourtant il continue à commander et décide lui-même de ce qui adviendra de son cœur.',q:'Formulez mentalement X → POURTANT → Y. Quelle question en découle le mieux ?',opts:['Comment le poète raconte-t-il une bataille ?','Comment l’agonie et la défaite deviennent-elles pourtant l’affirmation d’une puissance héroïque ?','Pourquoi Hialmar est-il amoureux ?'],a:1,why:'Le problème naît de la coexistence de la défaite physique et d’une puissance qui persiste. C’est ce rapport qu’il faut expliquer.'},
{name:'Transfert',quote:'Un lieu banal, pauvre et quotidien est décrit avec une précision telle qu’il devient l’objet d’un désir presque irréel.',q:'Sans formule fournie, qu’est-ce qui demande le plus clairement une explication ?',opts:['La description d’un lieu','La pauvreté du lieu','Un réel médiocre devenu objet de fascination'],a:2,why:'Vous transférez le geste : partir non du thème, mais de ce que le texte produit contre ce qu’on pouvait attendre.'}]},
plan:{title:'Construire.',bous:['Une problématique déjà formulée.','Vous choisissez des parties qui répondent, dans le bon ordre.','Un plan de réponses, pas de thèmes.'],lede:'Une grande partie n’est pas un thème : c’est une réponse nécessaire à la problématique.',levels:['DISTINGUER','CHOISIR','ORDONNER','COMPLÉTER','CONSTRUIRE'],items:[
{name:'Hialmar',quote:'Problématique : comment la défaite physique de Hialmar devient-elle l’affirmation de sa puissance ?',q:'Quelle proposition constitue une vraie première réponse ?',opts:['I. La défaite est d’abord rendue pleinement sensible dans le corps du guerrier.','I. Le champ lexical de la mort et du sang domine tout le début du poème.','I. Les figures de style rendent le champ de bataille vivant et effrayant.'],a:0,why:'A répond à la question : elle installe la défaite que la suite va dépasser. B et C décrivent des moyens, pas une réponse.'},
{name:'Plan',quote:'Problématique : comment une scène quotidienne devient-elle inquiétante ?',q:'Quelle partie est seulement thématique ?',opts:['I. Le cadre quotidien est d’abord solidement installé.','II. Des anomalies discrètes fissurent cette normalité.','II. Les procédés d’écriture qui créent l’angoisse.'],a:2,why:'Un catalogue de procédés ne constitue pas une réponse à la problématique.'},
{name:'Progression',quote:'I. Le texte installe un monde apparemment parfaitement ordinaire. III. L’ordinaire apparaît finalement comme le masque d’une menace.',q:'Quelle II rend la progression nécessaire ?',opts:['II. Le vocabulaire de la maison et des objets familiers.','II. Le personnage principal et ses habitudes de chaque jour.','II. Des détails de plus en plus étranges font naître le doute.'],a:2,why:'II doit expliquer le passage entre l’installation de l’ordinaire et la menace finale ; A et B reviennent à des thèmes.'},
{name:'Nécessité',quote:'Problématique : comment une déclaration d’amour prend-elle la forme paradoxale d’un combat ?',q:'Quelle architecture répond le mieux ?',opts:['I. Le langage de l’amour / II. Le langage de la guerre','I. La guerre envahit l’aveu / II. Elle intensifie l’amour','I. Le lexique des sentiments / II. Les figures du combat'],a:1,why:'Le plan ne juxtapose pas deux thèmes : il explique comment le combat devient une manière d’aimer.'}]},
transition:{title:'Enchaîner.',bous:['Une partie déjà établie.','Vous choisissez la question ouverte qui montre ce qu’elle n’explique pas.','Le passage vers la partie suivante.'],lede:'Une transition naît d’un manque : qu’est-ce que la réponse précédente n’explique pas encore ? Elle le dit en une question ouverte, posée entre deux parties.',levels:['REPÉRER','FORMULER','CHOISIR','ENCHAÎNER'],items:[
{name:'Hialmar',quote:'I. La violence de la défaite est pleinement installée.',q:'Quel manque construit réellement la suite ?',opts:['Quels autres procédés le poète emploie-t-il dans ce poème ?','Pourquoi Hialmar n’apparaît-il pourtant pas en vaincu ?','Que se passe-t-il ensuite sur le champ de bataille ?'],a:1,why:'Le manque restant revient à la problématique et révèle ce que I n’a pas encore expliqué.'},
{name:'Transition',quote:'I. Le récit rend la pauvreté des enfants immédiatement visible.',q:'Quelle question ouvre une II nécessaire si le texte fait ensuite de leur jeu un spectacle merveilleux ?',opts:['Comment cette pauvreté devient-elle un émerveillement ?','Quels adjectifs décrivent la pauvreté des deux enfants ?','Comment le texte est-il organisé en paragraphes ?'],a:0,why:'La transition n’annonce pas un thème : elle pose en question ouverte ce que la réponse précédente n’explique pas.'},
{name:'Réparer',quote:'« Nous avons vu la tristesse. Nous allons maintenant étudier l’espoir. »',q:'Que manque-t-il à cette transition ?',opts:['Un connecteur logique plus fort, comme « cependant ».','Une citation du texte, pour justifier ce passage à l’espoir.','Une question : que la tristesse n’explique-t-elle pas ?'],a:2,why:'La transition ne justifie pas à l’avance la partie suivante : elle pose, en une question ouverte, ce que la partie précédente n’explique pas.'},
{name:'Transfert',quote:'I. La scène semble d’abord comique. Problématique : comment le rire fait-il progressivement apparaître une violence sociale ?',q:'Quel manque faut-il formuler ?',opts:['Comment ce rire laisse-t-il voir une violence ?','Pourquoi le texte est-il si drôle dans les premières lignes ?','Quels personnages parlent dans la scène ?'],a:0,why:'Vous utilisez la problématique comme moteur : après I, on cherche ce qui reste à expliquer.'}]},
realisation:{title:'Comprendre ce que le texte fait.',bous:['Des éléments relevés dans un texte.','Vous dites ce que le texte fait avec eux.','Une réalisation, en une phrase.'],lede:'On appelle « réalisation » ce que le texte fait pour construire une idée. Le mot vient après le geste : d’abord comprendre l’action du texte, puis apprendre à la nommer.',levels:['COMPRENDRE','DISTINGUER','REGROUPER','FORMULER'],items:[
{name:'Hialmar',quote:'« Porte mon cœur » — impératif prononcé par le héros agonisant.',q:'Quelle proposition dit vraiment ce que le texte fait ?',opts:['L’impératif','Hialmar continue à commander au cœur même de son agonie.','Un effet héroïque'],a:1,why:'L’impératif est un élément textuel. La réalisation dit ce que le texte fait apparaître grâce à cet élément.'},
{name:'Procédé ou opération ?',quote:'Répétitions, phrases brèves, exclamations : la parole du personnage semble se briser.',q:'Quelle formulation dit ce que ces éléments font ensemble dans le texte ?',opts:['Le texte utilise des répétitions.','La parole se désorganise sous l’effet de l’émotion.','Il y a un rythme saccadé.'],a:1,why:'La réalisation synthétise plusieurs indices en une opération interprétable.'},
{name:'Regrouper',quote:'Un même objet est successivement nommé « jouet », « trésor », puis décrit comme un spectacle fascinant.',q:'Qu’est-ce que ces éléments permettent de montrer sur le texte ?',opts:['Le texte contient plusieurs noms.','Le regard transforme progressivement un objet pauvre en objet de fascination.','Le vocabulaire est varié.'],a:1,why:'On passe de la nomination des indices à ce qu’ils accomplissent ensemble.'},
{name:'Transfert',quote:'Une description multiplie d’abord les mesures exactes, puis glisse vers des comparaisons irréelles.',q:'Qu’est-ce que vous pourriez montrer à partir de ces éléments ?',opts:['Il y a des comparaisons.','La précision réaliste se dérègle progressivement et ouvre la description à l’imaginaire.','Le texte décrit un lieu.'],a:1,why:'La réalisation est une phrase dynamique : elle formule une opération du texte.'}]},
preuve:{title:'Prouver.',bous:['Une réalisation et un élément du texte.','Vous reliez l’élément, le procédé et l’effet ici.','Une analyse qui prouve.'],lede:'Réalisation (ce que le texte fait) → élément textuel → procédé → effet ici : une chaîne d’analyse qui ne saute aucune étape.',levels:['SÉLECTIONNER','RELIER','INTERPRÉTER','CONSTRUIRE'],items:[
{name:'Hialmar',quote:'Réalisation : Hialmar continue à commander. Élément : « Porte mon cœur », impératif.',q:'Quel effet est le plus précis ?',opts:['Cela produit un effet héroïque.','La mort ne lui retire pas sa puissance : agonisant, il reste celui qui ordonne et décide.','Cela montre un impératif.'],a:1,why:'Un effet doit dire ce que l’élément change dans notre compréhension du texte, pas répéter le procédé.'},
{name:'Élément textuel',quote:'Réalisation : le lieu familier devient progressivement menaçant.',q:'Quel élément prouverait le mieux cette réalisation ?',opts:['Le texte comporte trois paragraphes.','Des adjectifs rassurants sont progressivement remplacés par un lexique de l’ombre et de l’enfermement.','L’auteur emploie des mots.'],a:1,why:'L’élément doit être précisément observable et pertinent pour la réalisation défendue.'},
{name:'Chaîne',quote:'« Il rit. Il rit encore. Personne ne répond. »',q:'Quelle chaîne est la plus complète ?',opts:['Répétition → insistance.','Le rire devient mécanique → répétition de « il rit » et phrases brèves → le comique se vide progressivement de sa légèreté et devient inquiétant.','Phrases brèves → rythme rapide.'],a:1,why:'La chaîne complète articule opération, preuve et conséquence interprétative.'},
{name:'Réparer',quote:'« Le champ lexical de la guerre montre le champ lexical de la guerre. »',q:'Quel est le défaut principal ?',opts:['La citation est trop courte.','L’effet ne produit aucune interprétation : il répète l’élément textuel.','Il manque une problématique dans la phrase.'],a:1,why:'L’analyse doit franchir une étape : qu’est-ce que ce choix de mots change dans le sens ou l’effet du passage ?'}]},
commentaire:{title:'Commenter.',bous:['Les gestes travaillés un par un.','Vous les remettez dans l’ordre du devoir.','La méthode complète, prête pour un texte inconnu.'],lede:'Réassemblez les gestes : problématique, réponses nécessaires, transitions, réalisations, preuves.',levels:['ASSEMBLER','HIÉRARCHISER','TRANSFÉRER'],items:[
{name:'Assembler',quote:'Vous avez une problématique solide et trois grandes parties.',q:'Quelle étape vient logiquement avant la rédaction ?',opts:['Chercher des synonymes pour l’introduction','Préciser, dans chaque partie, ce que le texte fait et quels éléments précis permettent de le montrer','Rédiger immédiatement la conclusion'],a:1,why:'Avant de rédiger, il faut décliner chaque grande réponse du plan en analyses précises : ce que le texte fait, ce qui le montre et l’effet produit.'},
{name:'Hiérarchiser',quote:'Vous avez dix observations justes sur le texte.',q:'Que faut-il éviter ?',opts:['Les regrouper selon ce qu’elles permettent de montrer sur le texte','Les classer selon les réponses nécessaires à la problématique','Les aligner dans l’ordre où elles vous sont venues'],a:2,why:'Le commentaire n’est pas le journal de vos trouvailles : les observations doivent servir une démonstration.'},
{name:'Transfert',quote:'Sujet inconnu : vous disposez de quatre heures.',q:'Quel ordre de travail correspond le mieux à la méthode ?',opts:['Procédés → introduction → plan','Lecture → problématique → réponses du plan → analyses précises du texte → rédaction','Conclusion → citations → problématique'],a:1,why:'Les outils sont maintenant réassemblés dans l’ordre qui construit le raisonnement.'}]},
corriger:{title:'Corriger.',bous:['Une copie avec une erreur.','Vous trouvez l’erreur, puis la réparation prioritaire.','Le réflexe de vous relire.'],lede:'Repérez la fausse note, expliquez-la, puis réparez-la.',levels:['DIAGNOSTIQUER','EXPLIQUER','RÉPARER'],items:[
{name:'Copie',quote:'Problématique : « Comment l’auteur parle-t-il de la pauvreté ? »',q:'Diagnostic ?',opts:['La question est grammaticalement incorrecte.','Elle nomme un thème mais ne fait pas apparaître ce qui, dans ce traitement de la pauvreté, demande une explication.','Elle est trop courte.'],a:1,why:'Une problématique n’est pas une question générale sur le sujet du texte.'},
{name:'Copie',quote:'I. La pauvreté — II. Les enfants — III. Les procédés',q:'Diagnostic ?',opts:['Le plan est trop long.','Les parties sont des thèmes ou catégories, pas des réponses successives à une problématique.','Il faut toujours deux parties.'],a:1,why:'Le nombre n’est pas le problème : c’est la fonction logique des parties.'},
{name:'Copie',quote:'« L’auteur utilise une métaphore, ce qui crée une métaphore. »',q:'Réparation prioritaire ?',opts:['Ajouter une seconde citation','Dire ce que la métaphore fait au sens, à la perception ou au mouvement du texte','Remplacer “auteur” par “écrivain”'],a:1,why:'L’effet doit interpréter, pas rebaptiser le procédé.'}]}
};

const atelierExtras={
problematique:[
{name:'Swift',quote:'« Tout homme désire vivre longtemps, mais aucun ne voudrait être vieux. »',q:'Quel est le vrai problème à expliquer ?',opts:['La vieillesse est désagréable.','Nous désirons la durée de la vie tout en refusant l’état auquel cette durée conduit.','Swift parle du temps.'],a:1,why:'La tension ne se réduit ni au thème du temps ni à un jugement sur la vieillesse : le même désir contient une contradiction.'},
{name:'Groucho Marx',quote:'La télévision est dite « éducative » parce qu’elle pousse le locuteur à quitter la pièce pour lire.',q:'Quelle attente est renversée ?',opts:['Un média éducatif devrait instruire par ce qu’il montre.','Lire est toujours supérieur à regarder.','La télévision est un objet technique.'],a:0,why:'L’aphorisme conserve le mot « éducative » mais renverse son fonctionnement attendu : elle éduque indirectement, en provoquant sa propre fuite.'},
{name:'Baudelaire',quote:'Deux enfants séparés par la richesse découvrent pourtant une même fascination dans le jeu.',q:'Quelle problématique est la plus féconde ?',opts:['Comment Baudelaire décrit-il deux enfants ?','Comment le jeu fait-il apparaître, à travers une scène d’inégalité sociale, une égalité inattendue du désir et du regard ?','Pourquoi les enfants aiment-ils les jouets ?'],a:1,why:'La deuxième question conserve ensemble l’inégalité donnée et l’égalité que la scène fait surgir.'},
{name:'Alain',quote:'Une vie entièrement délivrée des difficultés devrait sembler désirable ; elle produit pourtant l’ennui.',q:'Quel Y faut-il conserver ?',opts:['La vie est difficile.','L’absence de difficulté peut elle-même priver l’existence de son intérêt.','Les rois sont riches.'],a:1,why:'Y doit dire ce que le texte produit contre ce qu’on pouvait attendre, non un thème périphérique.'},
{name:'Montaigne · bac 2025',quote:'Nous jugeons volontiers un homme par son rang ; Montaigne réclame qu’on le juge par ses qualités propres.',q:'Quel écart structure le passage ?',opts:['Ancien / moderne','Valeur sociale attribuée / valeur propre de la personne','Riche / pauvre seulement'],a:1,why:'Le texte déplace le critère du jugement : de ce qui entoure l’homme vers ce qui lui appartient réellement.'}],
plan:[
{name:'Baudelaire',quote:'Problématique : comment une scène d’inégalité fait-elle surgir une égalité inattendue du désir ?',q:'Quelle première réponse prépare réellement la suite ?',opts:['I. Les deux enfants, l’un riche, l’autre pauvre, et leurs jouets.','I. Les comparaisons et les adjectifs qui décrivent le jardin.','I. Le récit rend d’abord l’inégalité immédiatement visible.'],a:2,why:'Il faut établir la force de l’inégalité : sans elle, l’égalité qui surgit ensuite n’aurait rien de surprenant.'},
{name:'Alain',quote:'Problématique : comment Alain renverse-t-il l’idée qu’une vie facile serait nécessairement heureuse ?',q:'Quelle II répond à ce que I laisse ouvert après avoir montré l’ennui d’une vie sans obstacle ?',opts:['II. Les exemples qu’Alain choisit pour illustrer son idée.','II. La difficulté devient une condition de l’action et du désir.','II. Le vocabulaire du bonheur et de l’ennui dans le texte.'],a:1,why:'La partie ne change pas de sujet : elle répond au problème rendu nécessaire par I.'},
{name:'Montaigne · bac 2025',quote:'I. Nos jugements sont faussés par les signes extérieurs du rang.',q:'Quelle II prolonge logiquement ?',opts:['II. Montaigne emploie des comparaisons pour convaincre.','II. Les puissants, leurs titres et leurs richesses.','II. Il propose de juger l’homme par ses qualités propres.'],a:2,why:'Après la critique d’un mauvais critère, il reste à comprendre par quoi Montaigne le remplace.'},
{name:'Perec · bac 2021',quote:'Problématique : comment le logement devient-il le révélateur d’une existence suspendue entre réel et désir ?',q:'Quel plan est le plus démonstratif ?',opts:['I. L’appartement exigu / II. Le jeune couple / III. Les objets désirés','I. Un réel décevant / II. Son double rêvé / III. Une vie suspendue','I. La description / II. Les procédés / III. Le sens du texte'],a:1,why:'Le deuxième plan fait progresser une interprétation ; les autres classent des éléments.'},
{name:'Racine · bac 2023',quote:'L’amour est établi comme réciproque, mais la séparation demeure.',q:'Quelle dernière partie devient nécessaire ?',opts:['III. Les pronoms personnels et le dialogue des amants.','III. L’amour partagé rend l’impossible tragique.','III. Bérénice, reine que l’on doit renvoyer de Rome.'],a:1,why:'La dernière réponse doit expliquer le sens produit par la coexistence de l’amour et de l’impossibilité.'}],
transition:[
{name:'Baudelaire',quote:'I. L’inégalité entre les enfants est rendue spectaculaire.',q:'Quel manque ouvre la suite ?',opts:['Comment le texte est-il ponctué dans tout ce passage ?','Qui sont les deux personnages de cette scène ?','Qu’est-ce qui peut rapprocher ces enfants séparés ?'],a:2,why:'Le manque réactive exactement la tension centrale du texte.'},
{name:'Alain',quote:'I. Une vie sans difficulté conduit à l’ennui.',q:'Quelle question rend II nécessaire ?',opts:['Pourquoi la difficulté peut-elle alors rendre heureux ?','Quels exemples Alain utilise-t-il pour le montrer ?','Que signifie le mot « roi » dans ce passage ?'],a:0,why:'La question part de ce que I a établi (l’ennui) et reste ouverte : la partie suivante y répond.'},
{name:'Perec · bac 2021',quote:'I. L’appartement réel est marqué par le provisoire et l’insuffisance.',q:'Que reste-t-il surtout à expliquer ?',opts:['Combien de meubles l’appartement contient-il ?','Pourquoi ce manque fait-il rêver au lieu d’agir ?','En quelle année le roman a-t-il été publié ?'],a:1,why:'Le texte ne se contente pas de constater le manque : il montre ce que ce manque fait à l’existence des personnages.'},
{name:'Racine · bac 2023',quote:'I. Titus et Bérénice manifestent la force persistante de leur amour.',q:'Quel manque conduit à II ?',opts:['Pourquoi les personnages parlent-ils en vers ?','Lequel des deux amants parle le plus longtemps ?','Pourquoi cet amour rend-il la séparation plus cruelle ?'],a:2,why:'Le paradoxe central réapparaît comme moteur de la progression.'},
{name:'Reprise',quote:'Transition : « La scène fait rire : comment ce rire peut-il laisser grandir un malaise ? »',q:'Quelle phrase ouvre le mieux la partie suivante ?',opts:['Nous allons maintenant étudier le malaise du texte.','Ce malaise naît du rire lui-même, qui se fige.','Le texte contient aussi des passages plus graves.'],a:1,why:'La partie suivante reprend le mot clé de la question, « malaise », et y répond aussitôt. A annonce sans répondre ; C change de sujet.'}],
realisation:[
{name:'L’Orage',quote:'Le vocabulaire météorologique revient dans le souvenir amoureux.',q:'Quelle formulation est une réalisation ?',opts:['Champ lexical de la météo.','La météorologie devient progressivement le langage du souvenir amoureux.','Il y a un effet poétique.'],a:1,why:'La réalisation dit ce que le texte fait ; le champ lexical est une preuve possible.'},
{name:'L’Orage',quote:'La chanson s’adresse à la femme absente.',q:'Quel énoncé dit ce que le texte fait ?',opts:['Une apostrophe.','La parole tente symboliquement de rejoindre celle qui a disparu.','Le mot « complainte ».'],a:1,why:'La réalisation ne nomme pas seulement la forme linguistique : elle formule son opération dans le texte.'},
{name:'Baudelaire',quote:'Le jouet pauvre est regardé avec une attention de plus en plus intense.',q:'Quelle réalisation rassemble ce mouvement ?',opts:['Description du jouet.','Le regard transforme un objet matériellement pauvre en objet de fascination.','Adjectifs mélioratifs.'],a:1,why:'La réalisation est dynamique et interprétative.'},
{name:'Racine · bac 2023',quote:'Les personnages réaffirment leur amour au moment même où la séparation se confirme.',q:'Quelle réalisation ?',opts:['Le champ lexical de l’amour.','La parole rapproche affectivement les amants tout en consacrant leur séparation.','Une scène tragique.'],a:1,why:'La formulation fait apparaître l’opération paradoxale de la scène.'},
{name:'Montaigne · bac 2025',quote:'Montaigne compare notre manière de juger les hommes à celle dont nous évaluons d’autres réalités.',q:'Quelle réalisation ?',opts:['Une comparaison.','La comparaison dénaturalise nos critères sociaux et les rend soudain discutables.','Un exemple.'],a:1,why:'La comparaison est l’élément ; la réalisation dit ce qu’elle permet au raisonnement de faire.'}],
preuve:[
{name:'L’Orage',quote:'Réalisation : l’orage et l’amour finissent par se confondre dans l’écriture.',q:'Quel type d’élément est le plus pertinent ?',opts:['Le double sens d’une expression qui appartient à la fois à la météo et à l’amour.','Le nombre de strophes seulement.','Le nom de l’auteur.'],a:0,why:'L’élément doit matérialiser précisément la fusion des deux domaines.'},
{name:'Baudelaire',quote:'Réalisation : l’inégalité sociale est d’abord rendue visible.',q:'Quel élément textuel serait le plus probant ?',opts:['La juxtaposition de détails opposant richesse et pauvreté des deux enfants.','Une virgule isolée.','Le titre seulement.'],a:0,why:'La preuve doit correspondre exactement à l’opération formulée.'},
{name:'Alain',quote:'Réalisation : la facilité absolue est rendue stérile.',q:'Quel effet faut-il viser ?',opts:['Cela montre qu’il y a un exemple.','La valeur habituelle de la facilité est renversée : ce qui semblait désirable devient une menace pour le désir d’agir.','Cela produit une figure de style.'],a:1,why:'L’effet interprète ce que la réalisation change dans notre compréhension.'},
{name:'Perec · bac 2021',quote:'Élément : accumulation de réparations possibles, puis constat de leur non-réalisation.',q:'Quel effet ?',opts:['Le texte contient une accumulation.','Le logement apparaît comme un espace où le possible prolifère mais où l’action reste suspendue.','Le rythme est long.'],a:1,why:'L’effet relie la forme à la logique existentielle du passage.'},
{name:'Chaîne complète',quote:'Le personnage donne encore des ordres alors qu’il agonise.',q:'Quelle chaîne est la plus rigoureuse ?',opts:['Impératif → autorité.','Hialmar maintient son pouvoir d’action → impératif adressé au corbeau → l’agonie physique ne suffit pas à faire de lui un vaincu.','Mort → tristesse.'],a:1,why:'La chaîne part d’une opération, l’ancre dans le texte et formule ce que cette preuve change dans l’interprétation.'}],
commentaire:[
{name:'Plan détaillé',quote:'Vous avez trois grandes réponses nécessaires.',q:'Que faut-il maintenant produire dans chacune ?',opts:['Une liste de procédés sans hiérarchie.','Deux ou trois réalisations, chacune prouvée par des éléments textuels et interprétée par ses effets.','Une nouvelle problématique.'],a:1,why:'Le plan détaillé descend de la réponse globale vers les opérations précises du texte.'},
{name:'Rédaction',quote:'Votre plan détaillé est complet.',q:'Que devient-il dans la rédaction ?',opts:['Une suite de titres visibles.','Une démonstration continue : affirmation interprétative, explication de sa nécessité, analyse textuelle.','Une paraphrase du texte.'],a:1,why:'La rédaction met en discours la structure déjà construite ; elle ne recommence pas la recherche.'},
{name:'Introduction',quote:'Vous connaissez désormais le problème précis du texte.',q:'Quelle fonction doit garder l’introduction ?',opts:['Accumuler des connaissances historiques.','Installer le texte et conduire clairement jusqu’à la nécessité de la problématique.','Donner toutes les conclusions du commentaire.'],a:1,why:'L’introduction prépare la question qui organise le raisonnement.'},
{name:'Mode Bac',quote:'Vous découvrez un texte inconnu.',q:'Quel premier réflexe protège le mieux contre le catalogue de procédés ?',opts:['Surligner toutes les figures de style.','Chercher ce qu’on pouvait attendre, et ce que le texte produit.','Rédiger immédiatement une introduction.'],a:1,why:'Le relevé devient utile lorsqu’il sert une question de lecture déjà construite.'},
{name:'Autonomie',quote:'Vous reconnaissez parfaitement une correction déjà lue.',q:'Pourquoi cela ne suffit-il pas ?',opts:['Parce qu’il faut mémoriser davantage.','Parce que l’acquisition se vérifie par le transfert du geste à un texte inconnu.','Parce qu’une correction est toujours fausse.'],a:1,why:'La finalité des gammes est l’autonomie, non la reconnaissance d’un corrigé.'}],
corriger:[
{name:'Fausse problématique',quote:'« Comment l’auteur utilise-t-il des procédés pour rendre son texte intéressant ? »',q:'Quelle réparation ?',opts:['Ajouter le nom de trois procédés.','Revenir à la tension précise du texte : qu’est-ce qui y demande réellement une explication ?','Remplacer “intéressant” par “beau”.'],a:1,why:'La question générique ne peut organiser aucun texte en particulier.'},
{name:'Fausse partie',quote:'II. Les figures de style.',q:'Pourquoi est-ce une fausse partie ?',opts:['Parce qu’une partie doit être longue.','Parce qu’elle classe des moyens au lieu d’apporter une réponse nécessaire à la problématique.','Parce qu’il ne faut jamais parler de figures.'],a:1,why:'Les procédés peuvent être analysés, mais à l’intérieur d’une réponse interprétative.'},
{name:'Fausse transition',quote:'« Après avoir étudié le décor, nous verrons maintenant le personnage. »',q:'Que faut-il réparer ?',opts:['Le futur.','Le lien de nécessité : ce que le décor a établi et ce qu’il laisse encore inexpliqué.','Le mot personnage.'],a:1,why:'Une transition ne vaut pas par son annonce, mais par le problème qu’elle fait naître.'},
{name:'Fausse réalisation',quote:'« Une métaphore montre que le texte utilise une image. »',q:'Quel défaut ?',opts:['La réalisation se contente de renommer le procédé.','Il manque une date.','Il faut toujours deux métaphores.'],a:0,why:'Il faut dire ce que cette image accomplit dans le mouvement du texte.'},
{name:'Faux effet',quote:'« L’impératif produit un effet d’impératif. »',q:'Comment réparer ?',opts:['Chercher ce que l’impératif change dans le rapport de force, le portrait ou le sens.','Ajouter un adjectif.','Supprimer toute analyse grammaticale.'],a:0,why:'L’effet doit franchir le seuil de l’interprétation.'}]
};
Object.keys(atelierExtras).forEach(k=>{if(scales[k])scales[k].items=scales[k].items.concat(atelierExtras[k]);});

let qi=0;function param(){return new URLSearchParams(location.search).get('gamme')||'problematique'}
function renderQuiz(){const key=param(),s=scales[key]||scales.problematique,q=s.items[qi];const quote=document.getElementById('quote');if(!quote)return;document.getElementById('scale-kicker').textContent='GAMME · '+(s.levels[qi]||'ENTRAÎNER');document.getElementById('scale-title').textContent=s.title;document.getElementById('scale-lede').textContent=s.lede;const bo=document.getElementById('scale-boussole');if(bo&&s.bous){bo.innerHTML=['D’où vous partez','Ce que vous faites','Ce que vous obtenez'].map((t,j)=>`<p><b>${t}</b>${s.bous[j]}</p>`).join('');bo.hidden=false;}document.getElementById('level-note').textContent=`Niveau ${Math.min(qi+1,s.levels.length)} · ${s.levels[Math.min(qi,s.levels.length-1)]}`;document.getElementById('progress').textContent=`${qi+1} / ${s.items.length} · ${q.name}`;document.getElementById('question-title').textContent=q.q;document.getElementById('instruction').textContent='Choisissez la réponse la plus rigoureuse, puis lisez pourquoi.';quote.textContent=q.quote;document.getElementById('author').textContent=q.name.toUpperCase();const c=document.getElementById('choices');c.innerHTML='';q.opts.forEach((t,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${String.fromCharCode(65+i)}.</b> ${t}`;b.onclick=()=>answer(i,b,s,q);c.appendChild(b)});const f=document.getElementById('feedback');f.className='feedback';f.innerHTML='';const n=document.getElementById('nextquiz');n.className='quiz-next';}
function answer(i,b,s,q){document.querySelectorAll('#choices .choice').forEach((x,j)=>{x.disabled=true;if(j===q.a)x.classList.add('correct')});if(i!==q.a)b.classList.add('wrong');const f=document.getElementById('feedback');f.innerHTML=`<strong>${i===q.a?'Solide.':'À revoir.'}</strong><p>${q.why}</p>`;f.classList.add('show');const n=document.getElementById('nextquiz');n.textContent=qi<s.items.length-1?'Exercice suivant':'Rejouer la gamme';n.classList.add('show');try{const k='atelier-'+param();const old=JSON.parse(localStorage.getItem(k)||'{}');old[qi]=i===q.a;localStorage.setItem(k,JSON.stringify(old));}catch(e){}}
document.addEventListener('DOMContentLoaded',()=>{renderQuiz();const n=document.getElementById('nextquiz');if(n)n.onclick=()=>{const s=scales[param()]||scales.problematique;qi=qi<s.items.length-1?qi+1:0;renderQuiz()}});
(function(){const filters=document.querySelectorAll('.filter');const cards=document.querySelectorAll('.annale');if(!filters.length)return;filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;cards.forEach(c=>{c.style.display=(f==='all'||(c.dataset.tags||'').includes(f))?'block':'none';});}));})();
(function(){document.querySelectorAll('.reveal-btn').forEach(btn=>btn.addEventListener('click',()=>{const el=document.getElementById(btn.dataset.reveal);if(el){el.classList.add('show');btn.style.display='none';}}));})();
